version: '2'

services:
  zookeeper:
    restart: always
    image: "zookeeper:3.5"
    ports:
      - "2181"
  kafka:
    restart: always
    image: "wurstmeister/kafka"
    ports:
      - "9092"
    env_file:
      - kafka.env
    environment:
      HOSTNAME_COMMAND: "echo $$(hostname)"
#      BROKER_ID_COMMAND: "docker inspect --format '{{ .Name }}' $$(hostname) | awk -F_ '{ printf $$NF }'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes: #[HOST:CONTAINER]
      #- /var/lib/kafka:/
      - /var/log/kafka:/kafka