version: '3.1'

services:
  mongo1:
    restart: always
    image: mongo
    container_name: mongo
    ports:
      - 27017:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /home/mongo/datadir:/data/db
      - ./mongo.conf:/etc/mongo/mongo.conf
    command: mongod --config /etc/mongo/mongo.conf
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example