version: '2'

services:
  zk1:
    restart: always
    image: "zookeeper:3.4.13"
    container_name: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
  zk2:
    restart: always
    image: "zookeeper:3.4.13"
    container_name: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
  zk3:
    restart: always
    image: "zookeeper:3.4.13"
    container_name: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
  kafka1:
    restart: always
    image: "wurstmeister/kafka"
    container_name: kafka1
    ports:
      - "9092:9092"
      - "1099:1099"
#    env_file:
#      - kafka.env
    environment:
#      HOSTNAME_COMMAND: "echo $$(hostname)"
      KAFKA_BROKER_ID: 1
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.33.167
      KAFKA_ADVERTISED_HOST_NAME: 172.16.167.23
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
#      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka1 -Dcom.sun.management.jmxremote.rmi.port=1099"
#      JMX_PORT: 1099
    volumes: #[HOST:CONTAINER]
      - /var/log/kafka:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk1
      - zk2
      - zk3
  kafka2:
    restart: always
    image: "wurstmeister/kafka"
    container_name: kafka2
    ports:
      - "9093:9092"
      - "1098:1098"
    #    env_file:
    #      - kafka.env
    environment:
      #      HOSTNAME_COMMAND: "echo $$(hostname)"
      KAFKA_BROKER_ID: 2
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.33.167
      KAFKA_ADVERTISED_HOST_NAME: 172.16.167.23
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
#      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka2 -Dcom.sun.management.jmxremote.rmi.port=1098"
#      JMX_PORT: 1098
    volumes: #[HOST:CONTAINER]
      - /var/log/kafka:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk1
      - zk2
      - zk3
  kafka3:
    restart: always
    image: "wurstmeister/kafka"
    container_name: kafka3
    ports:
      - "9094:9092"
      - "1097:1097"
    #    env_file:
    #      - kafka.env
    environment:
      #      HOSTNAME_COMMAND: "echo $$(hostname)"
      KAFKA_BROKER_ID: 3
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.33.167
      KAFKA_ADVERTISED_HOST_NAME: 172.16.167.23
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
#      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka3 -Dcom.sun.management.jmxremote.rmi.port=1097"
#      JMX_PORT: 1097
    volumes: #[HOST:CONTAINER]
      - /var/log/kafka:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk1
      - zk2
      - zk3